// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AlphabetList: typeof import('./src/components/Header/AlphabetList.vue')['default']
    ArtistItem: typeof import('./src/components/Artist/ArtistItem.vue')['default']
    ArtistList: typeof import('./src/components/Artist/ArtistList.vue')['default']
    Button: typeof import('./src/components/Base/Button.vue')['default']
    Container: typeof import('./src/components/Base/Container.vue')['default']
    FloatInput: typeof import('./src/components/Base/FloatInput.vue')['default']
    Header: typeof import('./src/components/Header/Header.vue')['default']
    HeaderActionSection: typeof import('./src/components/Header/HeaderActionSection.vue')['default']
    HeaderNav: typeof import('./src/components/Header/HeaderNav.vue')['default']
    HeaderNavItem: typeof import('./src/components/Header/HeaderNavItem.vue')['default']
    Heading: typeof import('./src/components/Base/Heading.vue')['default']
    InstrumentsPicker: typeof import('./src/components/Profile/InstrumentsPicker.vue')['default']
    LastSongsTable: typeof import('./src/components/Tables/LastSongsTable.vue')['default']
    Link: typeof import('./src/components/Base/Link.vue')['default']
    LoginForm: typeof import('./src/components/Auth/LoginForm.vue')['default']
    ProfileEditForm: typeof import('./src/components/Profile/ProfileEditForm.vue')['default']
    RegisterForm: typeof import('./src/components/Auth/RegisterForm.vue')['default']
    RequestOverview: typeof import('./src/components/Request/RequestOverview.vue')['default']
    RichTextEditor: typeof import('./src/components/Base/RichTextEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchSectionTitle: typeof import('./src/components/Search/SearchSectionTitle.vue')['default']
    Sidebar: typeof import('./src/components/Base/Sidebar.vue')['default']
    SongForm: typeof import('./src/components/Song/SongForm.vue')['default']
    SongItem: typeof import('./src/components/Song/SongItem.vue')['default']
    SongList: typeof import('./src/components/Song/SongList.vue')['default']
    SongsTable: typeof import('./src/components/Tables/SongsTable.vue')['default']
    ThumbsIcon: typeof import('./src/components/Request/ThumbsIcon.vue')['default']
    TopList: typeof import('./src/components/Tables/TopList.vue')['default']
    TopUsersTable: typeof import('./src/components/Tables/TopUsersTable.vue')['default']
    Welcome: typeof import('./src/components/Home/Welcome.vue')['default']
  }
}

export {}
