// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core';

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Container: typeof import('./src/components/Container.vue')['default'];
    Header: typeof import('./src/components/Header/Header.vue')['default'];
    HeaderLink: typeof import('./src/components/Header/HeaderLink.vue')['default'];
    HeaderNav: typeof import('./src/components/Header/HeaderNav.vue')['default'];
    HeaderNavItem: typeof import('./src/components/Header/HeaderNavItem.vue')['default'];
    Link: typeof import('./src/components/Link.vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
  }
}

export {};
