// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Container: typeof import('./src/components/Base/Container.vue')['default']
    FloatInput: typeof import('./src/components/Base/FloatInput.vue')['default']
    Header: typeof import('./src/components/Header/Header.vue')['default']
    HeaderActionSection: typeof import('./src/components/Header/HeaderActionSection.vue')['default']
    HeaderNav: typeof import('./src/components/Header/HeaderNav.vue')['default']
    HeaderNavItem: typeof import('./src/components/Header/HeaderNavItem.vue')['default']
    Link: typeof import('./src/components/Base/Link.vue')['default']
    RichTextEditor: typeof import('./src/components/Base/RichTextEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
